//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplexWriter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über das Programm.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% im Acrobat Reader.
        /// </summary>
        public static string AcrobatSize {
            get {
                return ResourceManager.GetString("AcrobatSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Name hinzufügen.
        /// </summary>
        public static string AddAsName {
            get {
                return ResourceManager.GetString("AddAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charaktere an die Geschichte anfügen.
        /// </summary>
        public static string AddCharactersToStory {
            get {
                return ResourceManager.GetString("AddCharactersToStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Namen hinzufügen.
        /// </summary>
        public static string AddNewName {
            get {
                return ResourceManager.GetString("AddNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahlstil hinzunehmen.
        /// </summary>
        public static string AddSelectedStyle {
            get {
                return ResourceManager.GetString("AddSelectedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektierten Text als Name hinzufügen.
        /// </summary>
        public static string AddSelectedText {
            get {
                return ResourceManager.GetString("AddSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort beim Wechsel von Tabs anzeigen.
        /// </summary>
        public static string AksForPasswordTabs {
            get {
                return ResourceManager.GetString("AksForPasswordTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Passworthinweise erlauben.
        /// </summary>
        public static string AllowEmptyPasswordHint {
            get {
                return ResourceManager.GetString("AllowEmptyPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Stile sind bereits aktuell.
        /// </summary>
        public static string AllStylesUpToDate {
            get {
                return ResourceManager.GetString("AllStylesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immer im Vordergrund anzeigen.
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antagonist.
        /// </summary>
        public static string Antagonists {
            get {
                return ResourceManager.GetString("Antagonists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aussehen:.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort abfragen.
        /// </summary>
        public static string AskForPassword {
            get {
                return ResourceManager.GetString("AskForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &quot;{0}&quot; wurde automatisch gespeichert.
        /// </summary>
        public static string AutomaticSavedMessage {
            get {
                return ResourceManager.GetString("AutomaticSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können sie die Anführungszeichen (doppelt und einzelnd) angeben, die im Dokument verwendet werden sollen. 
        ///Beachten sie aber, dass bisherige Anführungszeichen nicht verändert werden..
        /// </summary>
        public static string BacketDescriptions {
            get {
                return ResourceManager.GetString("BacketDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarz als Hintergrund.
        /// </summary>
        public static string BlackBackground {
            get {
                return ResourceManager.GetString("BlackBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarz-Weiß (Vorschau nicht betroffen).
        /// </summary>
        public static string BlackWhite {
            get {
                return ResourceManager.GetString("BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocktext.
        /// </summary>
        public static string BlockText {
            get {
                return ResourceManager.GetString("BlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettgedruckter Text.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fett an / aus.
        /// </summary>
        public static string BoldOnOf {
            get {
                return ResourceManager.GetString("BoldOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groß- und Kleinschreibung.
        /// </summary>
        public static string CaseSensitivity {
            get {
                return ResourceManager.GetString("CaseSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentrierter Text.
        /// </summary>
        public static string CenteredText {
            get {
                return ResourceManager.GetString("CenteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrundfarbe ändern....
        /// </summary>
        public static string ChangeBackColor {
            get {
                return ResourceManager.GetString("ChangeBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vordergrundfarbe ändern....
        /// </summary>
        public static string ChangeForeColor {
            get {
                return ResourceManager.GetString("ChangeForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergeben / ändern.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegen ungespeicherte Änderungen der Datei &quot;{0}&quot; vor!
        ///
        ///Sollen diese gespeichert werden?.
        /// </summary>
        public static string ChangesInFile {
            get {
                return ResourceManager.GetString("ChangesInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Datei erstellen.
        /// </summary>
        public static string ChrateNewFile {
            get {
                return ResourceManager.GetString("ChrateNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trotzdem beenden.
        /// </summary>
        public static string CloseAnyway {
            get {
                return ResourceManager.GetString("CloseAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle bis auf dieses schließen.
        /// </summary>
        public static string CloseOther {
            get {
                return ResourceManager.GetString("CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließende Klammern.
        /// </summary>
        public static string ClosingBrackets {
            get {
                return ResourceManager.GetString("ClosingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle zusammenklappen.
        /// </summary>
        public static string CollapsAll {
            get {
                return ResourceManager.GetString("CollapsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe:.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationsordner.
        /// </summary>
        public static string ConfigurationFolder {
            get {
                return ResourceManager.GetString("ConfigurationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textkorrektur.
        /// </summary>
        public static string CorrectText {
            get {
                return ResourceManager.GetString("CorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Element erstellen.
        /// </summary>
        public static string CreateNewElement {
            get {
                return ResourceManager.GetString("CreateNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strg+&lt;Nummer&gt;.
        /// </summary>
        public static string CtrlNumber {
            get {
                return ResourceManager.GetString("CtrlNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strg+Shift+&lt;Nummer&gt;.
        /// </summary>
        public static string CtrlShiftNumber {
            get {
                return ResourceManager.GetString("CtrlShiftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strg + Shift +V.
        /// </summary>
        public static string CtrlShiftV {
            get {
                return ResourceManager.GetString("CtrlShiftV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währung.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschneiden.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrift verkleinern.
        /// </summary>
        public static string DecreaseFOnt {
            get {
                return ResourceManager.GetString("DecreaseFOnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstand rechts verkleinern.
        /// </summary>
        public static string DecreaseRighSpace {
            get {
                return ResourceManager.GetString("DecreaseRighSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstand verringern.
        /// </summary>
        public static string DecreaseSpace {
            get {
                return ResourceManager.GetString("DecreaseSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom vergrößern.
        /// </summary>
        public static string DecZoom {
            get {
                return ResourceManager.GetString("DecZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag löschen.
        /// </summary>
        public static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von der Festplatte löschen.
        /// </summary>
        public static string DeleteFromDrive {
            get {
                return ResourceManager.GetString("DeleteFromDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild löschen.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen?.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wörterbuch.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diverse.
        /// </summary>
        public static string Diverse {
            get {
                return ResourceManager.GetString("Diverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelklick, um ein Bild zu öffnen.
        /// </summary>
        public static string DoubleClickTooltip {
            get {
                return ResourceManager.GetString("DoubleClickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeichnungen und Icons.
        /// </summary>
        public static string DrawingsAndIcons {
            get {
                return ResourceManager.GetString("DrawingsAndIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag bearbeiten.
        /// </summary>
        public static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeitungsmodus ein/aus.
        /// </summary>
        public static string EditOnOf {
            get {
                return ResourceManager.GetString("EditOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemente zum Einfügen anzeigen.
        /// </summary>
        public static string ElementsForInsert {
            get {
                return ResourceManager.GetString("ElementsForInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeren.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Datei.
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Eintrag wird zum Wörterbuch hinzugefügt.
        /// </summary>
        public static string EntryIsAddedToDictionary {
            get {
                return ResourceManager.GetString("EntryIsAddedToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Eintrag wird zur Namensliste hinzugefügt.
        /// </summary>
        public static string EntryIsAddedToNames {
            get {
                return ResourceManager.GetString("EntryIsAddedToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Kopieren des Stils ist ein Fehler aufgetreten.
        ///
        ///Er wurde folglich nicht hinzugefügt..
        /// </summary>
        public static string ErrorWhileStyleCopy {
            get {
                return ResourceManager.GetString("ErrorWhileStyleCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle expandieren.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportieren....
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass sie die Datei unwiederruflich löschen wollen?
        ///Dieser Vorgang lässt sich nicht wieder rückgängig machen!.
        /// </summary>
        public static string FileDeleteQuestion {
            get {
                return ResourceManager.GetString("FileDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei {0} von {1} (&quot;{2)}&quot;) wird geladen.
        /// </summary>
        public static string FileIsLoadedLarge {
            get {
                return ResourceManager.GetString("FileIsLoadedLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &quot;{0}&quot; ist bereits offen.
        ///
        ///Damit Sie die Daten nicht versehentlich überschreiben, wurde die Datei kein 2. Mal geöffnet..
        /// </summary>
        public static string FileIsOpen {
            get {
                return ResourceManager.GetString("FileIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &quot;{0}&quot; wurde geöffnet.
        /// </summary>
        public static string FileIsOpened {
            get {
                return ResourceManager.GetString("FileIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereits offen.
        /// </summary>
        public static string FileIsOpenTitle {
            get {
                return ResourceManager.GetString("FileIsOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &quot;{0}&quot; wurde gespeichert.
        /// </summary>
        public static string FileISSaved {
            get {
                return ResourceManager.GetString("FileISSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Daten würde eingefügt werden:.
        /// </summary>
        public static string FileWouldBeInserted {
            get {
                return ResourceManager.GetString("FileWouldBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Schriften der Datei &quot;{0}&quot; wurden angepasst.
        /// </summary>
        public static string FontIsUpdated {
            get {
                return ResourceManager.GetString("FontIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Schriftart &quot;Arial Unicode MS&quot; wurde nicht gefunden.
        ///Somit steht Ihnen der &quot;Standard-Schrift verwenden&quot;-Button nicht zur Verfügung.
        ///
        ///Kopieren sie die Schrift wenn gewünscht in den Ordner &quot;Fonts&quot;..
        /// </summary>
        public static string FontMissing {
            get {
                return ResourceManager.GetString("FontMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlende Schrift.
        /// </summary>
        public static string FontMissingTitle {
            get {
                return ResourceManager.GetString("FontMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftart:.
        /// </summary>
        public static string Fontstyle {
            get {
                return ResourceManager.GetString("Fontstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von Seite.
        /// </summary>
        public static string FromPage {
            get {
                return ResourceManager.GetString("FromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhand einer Referenzdatei.
        /// </summary>
        public static string FromReferenceFile {
            get {
                return ResourceManager.GetString("FromReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhand einer Stildatei.
        /// </summary>
        public static string FromStyleFile {
            get {
                return ResourceManager.GetString("FromStyleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idee.
        /// </summary>
        public static string Idea {
            get {
                return ResourceManager.GetString("Idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle ignorieren.
        /// </summary>
        public static string IgnorenAll {
            get {
                return ResourceManager.GetString("IgnorenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wichtige Funktionen.
        /// </summary>
        public static string ImportantFunctions {
            get {
                return ResourceManager.GetString("ImportantFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrift vergößern.
        /// </summary>
        public static string IncreaseFont {
            get {
                return ResourceManager.GetString("IncreaseFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstand rechts vergrößern.
        /// </summary>
        public static string IncreaseRighSpace {
            get {
                return ResourceManager.GetString("IncreaseRighSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstand vergrößern.
        /// </summary>
        public static string IncreaseSpace {
            get {
                return ResourceManager.GetString("IncreaseSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom verringer.
        /// </summary>
        public static string IncZoom {
            get {
                return ResourceManager.GetString("IncZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor eingerichtet.
        /// </summary>
        public static string InitEditor {
            get {
                return ResourceManager.GetString("InitEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenten initialisiert.
        /// </summary>
        public static string InitializedComponents {
            get {
                return ResourceManager.GetString("InitializedComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle entfernen wieder reinnehmen.
        /// </summary>
        public static string InsertDeleted {
            get {
                return ResourceManager.GetString("InsertDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügeoption: Nur Text.
        /// </summary>
        public static string InserTextOnly {
            get {
                return ResourceManager.GetString("InserTextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild einfügen....
        /// </summary>
        public static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes Sonderzeichen einfügen.
        /// </summary>
        public static string InsertLastUnicode {
            get {
                return ResourceManager.GetString("InsertLastUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonderzeichen einfügen....
        /// </summary>
        public static string InsertUnicode {
            get {
                return ResourceManager.GetString("InsertUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schräggestellter Text.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schräg stellen an / aus.
        /// </summary>
        public static string ItalicOnOf {
            get {
                return ResourceManager.GetString("ItalicOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastenkombination.
        /// </summary>
        public static string Keycode {
            get {
                return ResourceManager.GetString("Keycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null voranstellen.
        /// </summary>
        public static string LeadingZero {
            get {
                return ResourceManager.GetString("LeadingZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linksbündiger Text.
        /// </summary>
        public static string LeftText {
            get {
                return ResourceManager.GetString("LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach aktuellem Vorbild.
        /// </summary>
        public static string LikeThisOne {
            get {
                return ResourceManager.GetString("LikeThisOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werte verankern.
        /// </summary>
        public static string LinkValues {
            get {
                return ResourceManager.GetString("LinkValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemente geladen.
        /// </summary>
        public static string LoadElements {
            get {
                return ResourceManager.GetString("LoadElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden von{0}.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei laden....
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen geladen.
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Örtlichkeit.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit einem anderem Wörterbuch zusammenführen.
        /// </summary>
        public static string MergeDictionary {
            get {
                return ResourceManager.GetString("MergeDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldungen.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimieren.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name &quot;{0}&quot; ist bereits vorhanden und wird daher nicht noch einmal hinzugenommen..
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen mit Leerzeichen am Ende.
        /// </summary>
        public static string NameWithSpaceEnd {
            get {
                return ResourceManager.GetString("NameWithSpaceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen mit Leerzeichen an beiden Enden.
        /// </summary>
        public static string NameWithSpaces {
            get {
                return ResourceManager.GetString("NameWithSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namen mit Leerzeichen am Anfang.
        /// </summary>
        public static string NameWithSpaceStart {
            get {
                return ResourceManager.GetString("NameWithSpaceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde eine neue Datei erstellt.
        /// </summary>
        public static string NewFileCreated {
            get {
                return ResourceManager.GetString("NewFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXX_Neuer Stil {0:00}.
        /// </summary>
        public static string NewStyleTemplate {
            get {
                return ResourceManager.GetString("NewStyleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste Seite.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den aktuellen Text wurde kein Default- Stil angegeben.
        ///Bitte wählen sie erst einen Stil als default aus..
        /// </summary>
        public static string NoDefaultStyle {
            get {
                return ResourceManager.GetString("NoDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Default-Stil ausgewählt.
        /// </summary>
        public static string NoDefaultStyleTitle {
            get {
                return ResourceManager.GetString("NoDefaultStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Passworthinweise anzeigen.
        /// </summary>
        public static string NoPasswordHint {
            get {
                return ResourceManager.GetString("NoPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerierte Liste.
        /// </summary>
        public static string NumericList {
            get {
                return ResourceManager.GetString("NumericList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorkommen.
        /// </summary>
        public static string Occurance {
            get {
                return ResourceManager.GetString("Occurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alte Seitenzahlen beibehalten.
        /// </summary>
        public static string OldNumbering {
            get {
                return ResourceManager.GetString("OldNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparenz.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnende Klammern.
        /// </summary>
        public static string OpenBackets {
            get {
                return ResourceManager.GetString("OpenBackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wörterbucheditor öffnen.
        /// </summary>
        public static string OpenDictionary {
            get {
                return ResourceManager.GetString("OpenDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnet einen Dialog zum Bearbeiten des Wörterbuchs.
        /// </summary>
        public static string OpenDictionaryWindow {
            get {
                return ResourceManager.GetString("OpenDictionaryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namensliste öffnen.
        /// </summary>
        public static string OpenNameDictionary {
            get {
                return ResourceManager.GetString("OpenNameDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnet einen Dialog zum Bearbeiten der Namensliste.
        /// </summary>
        public static string OpenNameDictionaryWindow {
            get {
                return ResourceManager.GetString("OpenNameDictionaryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originale Schriftgröße.
        /// </summary>
        public static string OriginalFontSize {
            get {
                return ResourceManager.GetString("OriginalFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originalgröße.
        /// </summary>
        public static string OriginalSize {
            get {
                return ResourceManager.GetString("OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiteres.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Farben.
        /// </summary>
        public static string OwnColors {
            get {
                return ResourceManager.GetString("OwnColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Bereich mit Seitenumbruch erstellen.
        /// </summary>
        public static string PageBreak {
            get {
                return ResourceManager.GetString("PageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenzahloptionen.
        /// </summary>
        public static string PageNumberinOptions {
            get {
                return ResourceManager.GetString("PageNumberinOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mögliche Ersetzungen.
        /// </summary>
        public static string PossibleReplacements {
            get {
                return ResourceManager.GetString("PossibleReplacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorherige Seite.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckvorschau.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Programm dient nur der privaten Nutzung und darf nicht für kommerzielle Zwecke verwendet werden.
        ///Die Weitergabe darf nur unter Einhaltung dieser Regeln vorgenommen werden..
        /// </summary>
        public static string PrivateText {
            get {
                return ResourceManager.GetString("PrivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmierung.
        /// </summary>
        public static string Programing {
            get {
                return ResourceManager.GetString("Programing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protagonist.
        /// </summary>
        public static string Protagonists {
            get {
                return ResourceManager.GetString("Protagonists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur lesen.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernte Stile.
        /// </summary>
        public static string RemovedStyles {
            get {
                return ResourceManager.GetString("RemovedStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; löschen.
        /// </summary>
        public static string RemoveSpecial {
            get {
                return ResourceManager.GetString("RemoveSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stil entfernen?.
        /// </summary>
        public static string RemoveStyleQuestion {
            get {
                return ResourceManager.GetString("RemoveStyleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei umbenennen.
        /// </summary>
        public static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ersetzen.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Vorkommen ersetzen.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ersetzen?.
        /// </summary>
        public static string ReplaceQuestion {
            get {
                return ResourceManager.GetString("ReplaceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu starten.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen am Wörterbuch werden erst nach einem Neustart aktiv.
        ///Soll jetzt neu gestartet werden?.
        /// </summary>
        public static string RestartForChanges {
            get {
                return ResourceManager.GetString("RestartForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen an der Namensliste werden erst nach einem Neustart aktiv.
        ///Soll jetzt neu gestartet werden?.
        /// </summary>
        public static string RestartForNameChanges {
            get {
                return ResourceManager.GetString("RestartForNameChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Rechtsklick für weitere Optionen).
        /// </summary>
        public static string RightClickOptions {
            get {
                return ResourceManager.GetString("RightClickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsbündiger Text.
        /// </summary>
        public static string RightText {
            get {
                return ResourceManager.GetString("RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten sie die Benutzung des Stils ebenfalls entfernen?.
        /// </summary>
        public static string RomoveUsageAsWell {
            get {
                return ResourceManager.GetString("RomoveUsageAsWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als RTF Datei exportieren.
        /// </summary>
        public static string SaveAsRTF {
            get {
                return ResourceManager.GetString("SaveAsRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch speichern.
        /// </summary>
        public static string SaveAutomatical {
            get {
                return ResourceManager.GetString("SaveAutomatical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geänderte Dateien speicher.
        /// </summary>
        public static string SaveChanged {
            get {
                return ResourceManager.GetString("SaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegen Fehler beim Speichern von Dateien vor. Das hat zur Folge, das einige Dateien ungespeicherte Änderungen haben.
        ///Soll trotzdem beendet werden?.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei speichern unter....
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur speichern.
        /// </summary>
        public static string SaveOnly {
            get {
                return ResourceManager.GetString("SaveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern?.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheitseinstellungen.
        /// </summary>
        public static string SavetySettings {
            get {
                return ResourceManager.GetString("SavetySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherung.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variablen gesetzt.
        /// </summary>
        public static string SetVariables {
            get {
                return ResourceManager.GetString("SetVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Klick auf den Button zeigt &quot;Über mich&quot;).
        /// </summary>
        public static string ShowAbout {
            get {
                return ResourceManager.GetString("ShowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldungen ansehen....
        /// </summary>
        public static string ShowMessages {
            get {
                return ResourceManager.GetString("ShowMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen anzeigen.
        /// </summary>
        public static string ShowOptions {
            get {
                return ResourceManager.GetString("ShowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenanzahl anzeigent (Vorschau nicht betroffen).
        /// </summary>
        public static string ShowPageNumbering {
            get {
                return ResourceManager.GetString("ShowPageNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anführungszeichen anzeigen.
        /// </summary>
        public static string ShowQuotes {
            get {
                return ResourceManager.GetString("ShowQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche anzeigen.
        /// </summary>
        public static string ShowSearch {
            get {
                return ResourceManager.GetString("ShowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stilfenster anzeigen.
        /// </summary>
        public static string ShowStylesWindow {
            get {
                return ResourceManager.GetString("ShowStylesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML-Code des FlowDocuments anzeigen....
        /// </summary>
        public static string ShowXAML {
            get {
                return ResourceManager.GetString("ShowXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließende Klammern (einzeln).
        /// </summary>
        public static string SingleClosingBracket {
            get {
                return ResourceManager.GetString("SingleClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnende Klammern (einzeln).
        /// </summary>
        public static string SingleOpenBracket {
            get {
                return ResourceManager.GetString("SingleOpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einige Dateien wurden geändert. Sollen diese gespeichert werden?.
        /// </summary>
        public static string SomeFilesChanged {
            get {
                return ResourceManager.GetString("SomeFilesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ohne Anführungszeichen.
        /// </summary>
        public static string Speach {
            get {
                return ResourceManager.GetString("Speach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache mit Anfühgrungszeichen.
        /// </summary>
        public static string SpeachWithQuotes {
            get {
                return ResourceManager.GetString("SpeachWithQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache mit einfachen Anführungszeichen.
        /// </summary>
        public static string SpeacSimpleQuotes {
            get {
                return ResourceManager.GetString("SpeacSimpleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; zum Wörterbuch hinzufügen.
        /// </summary>
        public static string SpecialEntryAddedToDictionary {
            get {
                return ResourceManager.GetString("SpecialEntryAddedToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; zur Namensliste hinzufügen.
        /// </summary>
        public static string SpecialEntryAddedToNames {
            get {
                return ResourceManager.GetString("SpecialEntryAddedToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spezielle Tastenkombinationen.
        /// </summary>
        public static string SpecialKeycode {
            get {
                return ResourceManager.GetString("SpecialKeycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spezien.
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtschreibprüfung an / aus.
        /// </summary>
        public static string SpellCheckOnOf {
            get {
                return ResourceManager.GetString("SpellCheckOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard-Befehle.
        /// </summary>
        public static string StandardCommands {
            get {
                return ResourceManager.GetString("StandardCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es existiert bereits ein Stil mit diesem Namen.
        ///
        ///Soll der alte Stil ersetzt werden?.
        /// </summary>
        public static string StyleAlreadyExists {
            get {
                return ResourceManager.GetString("StyleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Stil mit den gewüschten Einstellungen wurde bereits unter dem Namen 
        ///&quot;{0}&quot;
        ///hinzugefügt!
        ///
        ///Bitte verwenden sie genannten Stil..
        /// </summary>
        public static string StyleExists {
            get {
                return ResourceManager.GetString("StyleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Stil wurde bereits ohne Namensangabe hinzugefügt.
        ///
        ///Dopplung der Stildaten ist nicht erlaubt..
        /// </summary>
        public static string StyleExistsWithoutName {
            get {
                return ResourceManager.GetString("StyleExistsWithoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stil &lt;Nummer&gt;.
        /// </summary>
        public static string StyleNumber {
            get {
                return ResourceManager.GetString("StyleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stil &lt;Nummer&gt; mit Anführungszeichen.
        /// </summary>
        public static string StyleNumberQuote {
            get {
                return ResourceManager.GetString("StyleNumberQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind sie sich sicher, dass sie alle Stile entfernen möchten?\nDieser Vorgang lässt sich nicht wieder rückgängig machen!.
        /// </summary>
        public static string StyleRemoveQuestion {
            get {
                return ResourceManager.GetString("StyleRemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Stil wirklich entfernt werden?.
        /// </summary>
        public static string StyleRemoveQuestionTitle {
            get {
                return ResourceManager.GetString("StyleRemoveQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie bitte einen Titel für den Stil ein.
        /// </summary>
        public static string StyleTitle {
            get {
                return ResourceManager.GetString("StyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden {0} Stil(e) entfernt und {1} hinzugefügt..
        /// </summary>
        public static string StyleUpdateInfo {
            get {
                return ResourceManager.GetString("StyleUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Stil &quot;{0}&quot; kommt {1} Mal im Dokument vor.
        /// </summary>
        public static string StyleUsageCount {
            get {
                return ResourceManager.GetString("StyleUsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erweiterter Personenkreis.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemfarben.
        /// </summary>
        public static string SystemColors {
            get {
                return ResourceManager.GetString("SystemColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Writer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis Seite.
        /// </summary>
        public static string ToPage {
            get {
                return ResourceManager.GetString("ToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsterstrichener Text.
        /// </summary>
        public static string Underlined {
            get {
                return ResourceManager.GetString("Underlined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstrichen an / aus.
        /// </summary>
        public static string UnderlineOnOf {
            get {
                return ResourceManager.GetString("UnderlineOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.etf.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht angegeben.
        /// </summary>
        public static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hintergrund anpassen.
        /// </summary>
        public static string UpdateBackground {
            get {
                return ResourceManager.GetString("UpdateBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollen alle Elemente, die den Stil verwenden ebenfalls angepasst werden?.
        /// </summary>
        public static string UpdateElements {
            get {
                return ResourceManager.GetString("UpdateElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftart anpassen....
        /// </summary>
        public static string UpdateFont {
            get {
                return ResourceManager.GetString("UpdateFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeilenabstand bestimmen....
        /// </summary>
        public static string UpdateLineSpacing {
            get {
                return ResourceManager.GetString("UpdateLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anführungszeichen anpassen....
        /// </summary>
        public static string UpdateQuotes {
            get {
                return ResourceManager.GetString("UpdateQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seitenbild anpassen....
        /// </summary>
        public static string UpdateSideImage {
            get {
                return ResourceManager.GetString("UpdateSideImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasserzeichen anpassen....
        /// </summary>
        public static string UpdateWatermark {
            get {
                return ResourceManager.GetString("UpdateWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard-Schrift verwenden.
        /// </summary>
        public static string UseDefaultFOnt {
            get {
                return ResourceManager.GetString("UseDefaultFOnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default-Stil anwenden.
        /// </summary>
        public static string UseDefaultStyle {
            get {
                return ResourceManager.GetString("UseDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgangsschrift verwenden.
        /// </summary>
        public static string UseStartFont {
            get {
                return ResourceManager.GetString("UseStartFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die zu speichernde Datei enthält ein Wasserzeichen. Dieses würde in dem Format nicht gespeichert werden.
        ///
        ///Wollen sie es trotzdem in dem Format speichern?.
        /// </summary>
        public static string WatermarkNotSupportedMessage {
            get {
                return ResourceManager.GetString("WatermarkNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganze Seite anzeigen.
        /// </summary>
        public static string WholePage {
            get {
                return ResourceManager.GetString("WholePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganzes Wort.
        /// </summary>
        public static string WholeWord {
            get {
                return ResourceManager.GetString("WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
