//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplexWriter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% in Acrobat Reader.
        /// </summary>
        public static string AcrobatSize {
            get {
                return ResourceManager.GetString("AcrobatSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as name.
        /// </summary>
        public static string AddAsName {
            get {
                return ResourceManager.GetString("AddAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert characters after the text is prodessed.
        /// </summary>
        public static string AddCharactersToStory {
            get {
                return ResourceManager.GetString("AddCharactersToStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new name.
        /// </summary>
        public static string AddNewName {
            get {
                return ResourceManager.GetString("AddNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected style.
        /// </summary>
        public static string AddSelectedStyle {
            get {
                return ResourceManager.GetString("AddSelectedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected text as new name.
        /// </summary>
        public static string AddSelectedText {
            get {
                return ResourceManager.GetString("AddSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password if the tab is changed.
        /// </summary>
        public static string AksForPasswordTabs {
            get {
                return ResourceManager.GetString("AksForPasswordTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow empty password hints.
        /// </summary>
        public static string AllowEmptyPasswordHint {
            get {
                return ResourceManager.GetString("AllowEmptyPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All styles are up to date.
        /// </summary>
        public static string AllStylesUpToDate {
            get {
                return ResourceManager.GetString("AllStylesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show always on top.
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antagonist.
        /// </summary>
        public static string Antagonists {
            get {
                return ResourceManager.GetString("Antagonists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance:.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for passwords.
        /// </summary>
        public static string AskForPassword {
            get {
                return ResourceManager.GetString("AskForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is saved automatically.
        /// </summary>
        public static string AutomaticSavedMessage {
            get {
                return ResourceManager.GetString("AutomaticSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  On this dialog you are able to define the quuotation marks that are used by the document.
        ///Please remember, that already inserted quotations are not updated..
        /// </summary>
        public static string BacketDescriptions {
            get {
                return ResourceManager.GetString("BacketDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a black background.
        /// </summary>
        public static string BlackBackground {
            get {
                return ResourceManager.GetString("BlackBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and White (not seen in the preview).
        /// </summary>
        public static string BlackWhite {
            get {
                return ResourceManager.GetString("BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block text.
        /// </summary>
        public static string BlockText {
            get {
                return ResourceManager.GetString("BlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Text.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string BoldOnOf {
            get {
                return ResourceManager.GetString("BoldOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitivity.
        /// </summary>
        public static string CaseSensitivity {
            get {
                return ResourceManager.GetString("CaseSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered Text.
        /// </summary>
        public static string CenteredText {
            get {
                return ResourceManager.GetString("CenteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change background color....
        /// </summary>
        public static string ChangeBackColor {
            get {
                return ResourceManager.GetString("ChangeBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change foreground color....
        /// </summary>
        public static string ChangeForeColor {
            get {
                return ResourceManager.GetString("ChangeForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set / change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes on the file &quot;{0}&quot;!
        ///
        ///Would you like to save them?.
        /// </summary>
        public static string ChangesInFile {
            get {
                return ResourceManager.GetString("ChangesInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new file.
        /// </summary>
        public static string ChrateNewFile {
            get {
                return ResourceManager.GetString("ChrateNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close anyway.
        /// </summary>
        public static string CloseAnyway {
            get {
                return ResourceManager.GetString("CloseAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all but this.
        /// </summary>
        public static string CloseOther {
            get {
                return ResourceManager.GetString("CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing brackets.
        /// </summary>
        public static string ClosingBrackets {
            get {
                return ResourceManager.GetString("ClosingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CollapsAll {
            get {
                return ResourceManager.GetString("CollapsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings folder.
        /// </summary>
        public static string ConfigurationFolder {
            get {
                return ResourceManager.GetString("ConfigurationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellchecker.
        /// </summary>
        public static string CorrectText {
            get {
                return ResourceManager.GetString("CorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new element.
        /// </summary>
        public static string CreateNewElement {
            get {
                return ResourceManager.GetString("CreateNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+&lt;Number&gt;.
        /// </summary>
        public static string CtrlNumber {
            get {
                return ResourceManager.GetString("CtrlNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+&lt;Number&gt;.
        /// </summary>
        public static string CtrlShiftNumber {
            get {
                return ResourceManager.GetString("CtrlShiftNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Shift +V.
        /// </summary>
        public static string CtrlShiftV {
            get {
                return ResourceManager.GetString("CtrlShiftV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease font.
        /// </summary>
        public static string DecreaseFOnt {
            get {
                return ResourceManager.GetString("DecreaseFOnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease right indent.
        /// </summary>
        public static string DecreaseRighSpace {
            get {
                return ResourceManager.GetString("DecreaseRighSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease indent.
        /// </summary>
        public static string DecreaseSpace {
            get {
                return ResourceManager.GetString("DecreaseSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease zoom.
        /// </summary>
        public static string DecZoom {
            get {
                return ResourceManager.GetString("DecZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry.
        /// </summary>
        public static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from file system.
        /// </summary>
        public static string DeleteFromDrive {
            get {
                return ResourceManager.GetString("DeleteFromDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diverse.
        /// </summary>
        public static string Diverse {
            get {
                return ResourceManager.GetString("Diverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open an image.
        /// </summary>
        public static string DoubleClickTooltip {
            get {
                return ResourceManager.GetString("DoubleClickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images and icons.
        /// </summary>
        public static string DrawingsAndIcons {
            get {
                return ResourceManager.GetString("DrawingsAndIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry.
        /// </summary>
        public static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable on / off.
        /// </summary>
        public static string EditOnOf {
            get {
                return ResourceManager.GetString("EditOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show insertable elements.
        /// </summary>
        public static string ElementsForInsert {
            get {
                return ResourceManager.GetString("ElementsForInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry is added to the dictionary.
        /// </summary>
        public static string EntryIsAddedToDictionary {
            get {
                return ResourceManager.GetString("EntryIsAddedToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry is added to the name list.
        /// </summary>
        public static string EntryIsAddedToNames {
            get {
                return ResourceManager.GetString("EntryIsAddedToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while coping the style. 
        ///
        ///The style is not added.
        /// </summary>
        public static string ErrorWhileStyleCopy {
            get {
                return ResourceManager.GetString("ErrorWhileStyleCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you like to delete the file? 
        ///The deletion is permanently..
        /// </summary>
        public static string FileDeleteQuestion {
            get {
                return ResourceManager.GetString("FileDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} of {1} (&quot;{2}&quot;) is loaded..
        /// </summary>
        public static string FileIsLoadedLarge {
            get {
                return ResourceManager.GetString("FileIsLoadedLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is alread open
        ///
        ///Opening the same file in two tabs is not supported..
        /// </summary>
        public static string FileIsOpen {
            get {
                return ResourceManager.GetString("FileIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File &quot;{0}&quot; is opened.
        /// </summary>
        public static string FileIsOpened {
            get {
                return ResourceManager.GetString("FileIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already open.
        /// </summary>
        public static string FileIsOpenTitle {
            get {
                return ResourceManager.GetString("FileIsOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is saved.
        /// </summary>
        public static string FileISSaved {
            get {
                return ResourceManager.GetString("FileISSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following data would be inserted:.
        /// </summary>
        public static string FileWouldBeInserted {
            get {
                return ResourceManager.GetString("FileWouldBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fonts for the file &quot;{0}&quot; were updated.
        /// </summary>
        public static string FontIsUpdated {
            get {
                return ResourceManager.GetString("FontIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font &quot;Arial Unicode MS&quot; is not found.
        ///For that reason, the &quot;standard font&quot; button is disabled.
        ///
        ///If you like to use it, copy it to the &quot;Fonts&quot; folder.
        /// </summary>
        public static string FontMissing {
            get {
                return ResourceManager.GetString("FontMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing font.
        /// </summary>
        public static string FontMissingTitle {
            get {
                return ResourceManager.GetString("FontMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style:.
        /// </summary>
        public static string Fontstyle {
            get {
                return ResourceManager.GetString("Fontstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Page.
        /// </summary>
        public static string FromPage {
            get {
                return ResourceManager.GetString("FromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From reference file.
        /// </summary>
        public static string FromReferenceFile {
            get {
                return ResourceManager.GetString("FromReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From style file.
        /// </summary>
        public static string FromStyleFile {
            get {
                return ResourceManager.GetString("FromStyleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hight.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea.
        /// </summary>
        public static string Idea {
            get {
                return ResourceManager.GetString("Idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore all.
        /// </summary>
        public static string IgnorenAll {
            get {
                return ResourceManager.GetString("IgnorenAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Functions.
        /// </summary>
        public static string ImportantFunctions {
            get {
                return ResourceManager.GetString("ImportantFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase font.
        /// </summary>
        public static string IncreaseFont {
            get {
                return ResourceManager.GetString("IncreaseFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase right indent.
        /// </summary>
        public static string IncreaseRighSpace {
            get {
                return ResourceManager.GetString("IncreaseRighSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase indent.
        /// </summary>
        public static string IncreaseSpace {
            get {
                return ResourceManager.GetString("IncreaseSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase zoom.
        /// </summary>
        public static string IncZoom {
            get {
                return ResourceManager.GetString("IncZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized editor.
        /// </summary>
        public static string InitEditor {
            get {
                return ResourceManager.GetString("InitEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized components.
        /// </summary>
        public static string InitializedComponents {
            get {
                return ResourceManager.GetString("InitializedComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore deleted.
        /// </summary>
        public static string InsertDeleted {
            get {
                return ResourceManager.GetString("InsertDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert option: text only.
        /// </summary>
        public static string InserTextOnly {
            get {
                return ResourceManager.GetString("InserTextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image....
        /// </summary>
        public static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert last used unicode.
        /// </summary>
        public static string InsertLastUnicode {
            get {
                return ResourceManager.GetString("InsertLastUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert unicode....
        /// </summary>
        public static string InsertUnicode {
            get {
                return ResourceManager.GetString("InsertUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic text.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic on / off.
        /// </summary>
        public static string ItalicOnOf {
            get {
                return ResourceManager.GetString("ItalicOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key code.
        /// </summary>
        public static string Keycode {
            get {
                return ResourceManager.GetString("Keycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add leading zero.
        /// </summary>
        public static string LeadingZero {
            get {
                return ResourceManager.GetString("LeadingZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left aligned text.
        /// </summary>
        public static string LeftText {
            get {
                return ResourceManager.GetString("LeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From current File.
        /// </summary>
        public static string LikeThisOne {
            get {
                return ResourceManager.GetString("LikeThisOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link values.
        /// </summary>
        public static string LinkValues {
            get {
                return ResourceManager.GetString("LinkValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load elements.
        /// </summary>
        public static string LoadElements {
            get {
                return ResourceManager.GetString("LoadElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading &quot;{0}&quot;.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file....
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge with an other dictionary.
        /// </summary>
        public static string MergeDictionary {
            get {
                return ResourceManager.GetString("MergeDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name &quot;{0}&quot; is already taken and can not be added twice..
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Dialog.
        /// </summary>
        public static string NameDialog {
            get {
                return ResourceManager.GetString("NameDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names with space as suffix.
        /// </summary>
        public static string NameWithSpaceEnd {
            get {
                return ResourceManager.GetString("NameWithSpaceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names with space on both ends.
        /// </summary>
        public static string NameWithSpaces {
            get {
                return ResourceManager.GetString("NameWithSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names with space as prefix.
        /// </summary>
        public static string NameWithSpaceStart {
            get {
                return ResourceManager.GetString("NameWithSpaceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new file is created.
        /// </summary>
        public static string NewFileCreated {
            get {
                return ResourceManager.GetString("NewFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXX_New style {0:00}.
        /// </summary>
        public static string NewStyleTemplate {
            get {
                return ResourceManager.GetString("NewStyleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default style defined for this text.
        ///Please choose a default style before using this feature..
        /// </summary>
        public static string NoDefaultStyle {
            get {
                return ResourceManager.GetString("NoDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default style defined.
        /// </summary>
        public static string NoDefaultStyleTitle {
            get {
                return ResourceManager.GetString("NoDefaultStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide password hints.
        /// </summary>
        public static string NoPasswordHint {
            get {
                return ResourceManager.GetString("NoPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric List.
        /// </summary>
        public static string NumericList {
            get {
                return ResourceManager.GetString("NumericList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurance.
        /// </summary>
        public static string Occurance {
            get {
                return ResourceManager.GetString("Occurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep old numbering.
        /// </summary>
        public static string OldNumbering {
            get {
                return ResourceManager.GetString("OldNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Brackets.
        /// </summary>
        public static string OpenBackets {
            get {
                return ResourceManager.GetString("OpenBackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open dictionary.
        /// </summary>
        public static string OpenDictionary {
            get {
                return ResourceManager.GetString("OpenDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the dialog for editing the dictionary.
        /// </summary>
        public static string OpenDictionaryWindow {
            get {
                return ResourceManager.GetString("OpenDictionaryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open name list.
        /// </summary>
        public static string OpenNameDictionary {
            get {
                return ResourceManager.GetString("OpenNameDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the dialog for editing the name list.
        /// </summary>
        public static string OpenNameDictionaryWindow {
            get {
                return ResourceManager.GetString("OpenNameDictionaryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original font size.
        /// </summary>
        public static string OriginalFontSize {
            get {
                return ResourceManager.GetString("OriginalFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        public static string OriginalSize {
            get {
                return ResourceManager.GetString("OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom colors.
        /// </summary>
        public static string OwnColors {
            get {
                return ResourceManager.GetString("OwnColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new paragraph with page break.
        /// </summary>
        public static string PageBreak {
            get {
                return ResourceManager.GetString("PageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page numbering settings.
        /// </summary>
        public static string PageNumberinOptions {
            get {
                return ResourceManager.GetString("PageNumberinOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible replacements.
        /// </summary>
        public static string PossibleReplacements {
            get {
                return ResourceManager.GetString("PossibleReplacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is written under a GNU General Public License and not for commercial usage.
        ///Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights..
        /// </summary>
        public static string PrivateText {
            get {
                return ResourceManager.GetString("PrivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programing.
        /// </summary>
        public static string Programing {
            get {
                return ResourceManager.GetString("Programing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protagonist.
        /// </summary>
        public static string Protagonists {
            get {
                return ResourceManager.GetString("Protagonists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed styles.
        /// </summary>
        public static string RemovedStyles {
            get {
                return ResourceManager.GetString("RemovedStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot;.
        /// </summary>
        public static string RemoveSpecial {
            get {
                return ResourceManager.GetString("RemoveSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove style?.
        /// </summary>
        public static string RemoveStyleQuestion {
            get {
                return ResourceManager.GetString("RemoveStyleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        public static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace?.
        /// </summary>
        public static string ReplaceQuestion {
            get {
                return ResourceManager.GetString("ReplaceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert foreground color.
        /// </summary>
        public static string RervertForeground {
            get {
                return ResourceManager.GetString("RervertForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changings on the dictionary are only available after restarting the programm.
        ///Would you like to restart ist?.
        /// </summary>
        public static string RestartForChanges {
            get {
                return ResourceManager.GetString("RestartForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changings on the name list are only available after restarting the programm.
        ///Would you like to restart ist?.
        /// </summary>
        public static string RestartForNameChanges {
            get {
                return ResourceManager.GetString("RestartForNameChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert background color.
        /// </summary>
        public static string RevertBackground {
            get {
                return ResourceManager.GetString("RevertBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click right for more options).
        /// </summary>
        public static string RightClickOptions {
            get {
                return ResourceManager.GetString("RightClickOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right aligned text.
        /// </summary>
        public static string RightText {
            get {
                return ResourceManager.GetString("RightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove all usages of the style as well?.
        /// </summary>
        public static string RomoveUsageAsWell {
            get {
                return ResourceManager.GetString("RomoveUsageAsWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as *.rtf.
        /// </summary>
        public static string SaveAsRTF {
            get {
                return ResourceManager.GetString("SaveAsRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save automatically.
        /// </summary>
        public static string SaveAutomatical {
            get {
                return ResourceManager.GetString("SaveAutomatical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changed files.
        /// </summary>
        public static string SaveChanged {
            get {
                return ResourceManager.GetString("SaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files could not be saved, because of errors happening during this operation.
        ///Would you like to close the program anyway?.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file as....
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save only.
        /// </summary>
        public static string SaveOnly {
            get {
                return ResourceManager.GetString("SaveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security settings.
        /// </summary>
        public static string SavetySettings {
            get {
                return ResourceManager.GetString("SavetySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables initialized.
        /// </summary>
        public static string SetVariables {
            get {
                return ResourceManager.GetString("SetVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click the buton to show &quot;About the programm&quot;).
        /// </summary>
        public static string ShowAbout {
            get {
                return ResourceManager.GetString("ShowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show messages....
        /// </summary>
        public static string ShowMessages {
            get {
                return ResourceManager.GetString("ShowMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show options.
        /// </summary>
        public static string ShowOptions {
            get {
                return ResourceManager.GetString("ShowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show page numbering (not shown in preview).
        /// </summary>
        public static string ShowPageNumbering {
            get {
                return ResourceManager.GetString("ShowPageNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show quotations.
        /// </summary>
        public static string ShowQuotes {
            get {
                return ResourceManager.GetString("ShowQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show search.
        /// </summary>
        public static string ShowSearch {
            get {
                return ResourceManager.GetString("ShowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show style window.
        /// </summary>
        public static string ShowStylesWindow {
            get {
                return ResourceManager.GetString("ShowStylesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show XAML code for the document....
        /// </summary>
        public static string ShowXAML {
            get {
                return ResourceManager.GetString("ShowXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing brackets (single).
        /// </summary>
        public static string SingleClosingBracket {
            get {
                return ResourceManager.GetString("SingleClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brackets (single).
        /// </summary>
        public static string SingleOpenBracket {
            get {
                return ResourceManager.GetString("SingleOpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files are changed. Would you like to save them?.
        /// </summary>
        public static string SomeFilesChanged {
            get {
                return ResourceManager.GetString("SomeFilesChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speach without quotes.
        /// </summary>
        public static string Speach {
            get {
                return ResourceManager.GetString("Speach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speach with quotes.
        /// </summary>
        public static string SpeachWithQuotes {
            get {
                return ResourceManager.GetString("SpeachWithQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speach with single quotes.
        /// </summary>
        public static string SpeacSimpleQuotes {
            get {
                return ResourceManager.GetString("SpeacSimpleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;{0}&quot; to the dictionary.
        /// </summary>
        public static string SpecialEntryAddedToDictionary {
            get {
                return ResourceManager.GetString("SpecialEntryAddedToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;{0}&quot; to the name list.
        /// </summary>
        public static string SpecialEntryAddedToNames {
            get {
                return ResourceManager.GetString("SpecialEntryAddedToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special key codes.
        /// </summary>
        public static string SpecialKeycode {
            get {
                return ResourceManager.GetString("SpecialKeycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell checking on / off.
        /// </summary>
        public static string SpellCheckOnOf {
            get {
                return ResourceManager.GetString("SpellCheckOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard commands.
        /// </summary>
        public static string StandardCommands {
            get {
                return ResourceManager.GetString("StandardCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the style is already taken.
        ///
        ///Would you like to replace the previous style?.
        /// </summary>
        public static string StyleAlreadyExists {
            get {
                return ResourceManager.GetString("StyleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A style with this settings is already defined under the name
        ///&quot;{0}&quot;
        ///
        ///Please use that style instead..
        /// </summary>
        public static string StyleExists {
            get {
                return ResourceManager.GetString("StyleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This style is added without a name. 
        ///
        ///Styles have to be unique to be registered..
        /// </summary>
        public static string StyleExistsWithoutName {
            get {
                return ResourceManager.GetString("StyleExistsWithoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style &lt;number&gt;.
        /// </summary>
        public static string StyleNumber {
            get {
                return ResourceManager.GetString("StyleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style &lt;number&gt; with quotation marks.
        /// </summary>
        public static string StyleNumberQuote {
            get {
                return ResourceManager.GetString("StyleNumberQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you like to remove the file?
        ///It is impossible to undone the operation..
        /// </summary>
        public static string StyleRemoveQuestion {
            get {
                return ResourceManager.GetString("StyleRemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you like to remove the style?.
        /// </summary>
        public static string StyleRemoveQuestionTitle {
            get {
                return ResourceManager.GetString("StyleRemoveQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title for your style.
        /// </summary>
        public static string StyleTitle {
            get {
                return ResourceManager.GetString("StyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} style(s) deleted and {1} added..
        /// </summary>
        public static string StyleUpdateInfo {
            get {
                return ResourceManager.GetString("StyleUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style &quot;{0}&quot; is used {1} times.
        /// </summary>
        public static string StyleUsageCount {
            get {
                return ResourceManager.GetString("StyleUsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support characters.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System colors.
        /// </summary>
        public static string SystemColors {
            get {
                return ResourceManager.GetString("SystemColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Writer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to page.
        /// </summary>
        public static string ToPage {
            get {
                return ResourceManager.GetString("ToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlined text.
        /// </summary>
        public static string Underlined {
            get {
                return ResourceManager.GetString("Underlined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;Underlined  on / off.
        /// </summary>
        public static string UnderlineOnOf {
            get {
                return ResourceManager.GetString("UnderlineOnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.etf.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset.
        /// </summary>
        public static string Unset {
            get {
                return ResourceManager.GetString("Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update background.
        /// </summary>
        public static string UpdateBackground {
            get {
                return ResourceManager.GetString("UpdateBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update all elements using this style as well?.
        /// </summary>
        public static string UpdateElements {
            get {
                return ResourceManager.GetString("UpdateElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update font....
        /// </summary>
        public static string UpdateFont {
            get {
                return ResourceManager.GetString("UpdateFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update line spacing....
        /// </summary>
        public static string UpdateLineSpacing {
            get {
                return ResourceManager.GetString("UpdateLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update quotation marks....
        /// </summary>
        public static string UpdateQuotes {
            get {
                return ResourceManager.GetString("UpdateQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update side image....
        /// </summary>
        public static string UpdateSideImage {
            get {
                return ResourceManager.GetString("UpdateSideImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update watermark....
        /// </summary>
        public static string UpdateWatermark {
            get {
                return ResourceManager.GetString("UpdateWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default font.
        /// </summary>
        public static string UseDefaultFOnt {
            get {
                return ResourceManager.GetString("UseDefaultFOnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default style.
        /// </summary>
        public static string UseDefaultStyle {
            get {
                return ResourceManager.GetString("UseDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used font:.
        /// </summary>
        public static string UsedFont {
            get {
                return ResourceManager.GetString("UsedFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use initial font.
        /// </summary>
        public static string UseStartFont {
            get {
                return ResourceManager.GetString("UseStartFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains a watermark, which is not supported by the used file format and would not be saved.
        ///
        ///Would you like to save it anyway?.
        /// </summary>
        public static string WatermarkNotSupportedMessage {
            get {
                return ResourceManager.GetString("WatermarkNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show whole page.
        /// </summary>
        public static string WholePage {
            get {
                return ResourceManager.GetString("WholePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole word.
        /// </summary>
        public static string WholeWord {
            get {
                return ResourceManager.GetString("WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
